apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - manifests/route.yaml
  - manifests/gateway.yaml
  - manifests/deployment_log.yaml
  - manifests/deployment_pong.yaml
  - manifests/configmap_log.yaml
  - manifests/confmap_postgres.yaml
  - manifests/secret_postgres.yaml
  - manifests/service_log.yaml
  - manifests/service_pong.yaml
  - manifests/service_postgres.yaml
  - manifests/statefulset.yaml
  - manifests/persistentvolumeclaim.yaml

images:
  - name: PROJECT/IMAGE_LOR
    newName: skinatro/log-output-read

  - name: PROJECT/IMAGE_LOG
    newName: skinatro/log-output-gen

  - name: PROJECT/IMAGE_PPA
    newName: skinatro/ping-pong-app
