apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pong-claim # name of the volume claim, this will be used in the deployment
  namespace: exercises
spec:
  #storageClassName: my-logs-pong-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi