apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: log-output-rollout
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 30s
        - analysis:
            templates:
              - templateName: pingpong-cpu-usage-rate
        - setWeight: 100
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-read
          image: skinatro/log-output-read:latest
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            httpGet:
              path: /healthz
              port: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: exercises-confmap
                  key: message
          volumeMounts:
            - name: shared-logs
              mountPath: /tmp/kube
            - name: confmap-vol
              mountPath: /etc/config

        - name: log-output-gen
          image: skinatro/log-output-gen:latest
          volumeMounts:
            - name: shared-logs
              mountPath: /tmp/kube

      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: confmap-vol
          configMap:
            name: exercises-confmap
