name: 'Build and Push Images'
on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: log-output-gen
            context: ./log_output
            dockerfile: Dockerfile.gen
            tag: skinatro/log-output-gen
            kustomize_image: PROJECT/IMAGE_LOG
          - name: log-output-read
            context: ./log_output
            dockerfile: Dockerfile.read
            tag: skinatro/log-output-read
            kustomize_image: PROJECT/IMAGE_LOR
          - name: ping-pong-app
            context: ./ping_pong_app
            dockerfile: Dockerfile
            tag: skinatro/ping-pong-app
            kustomize_image: PROJECT/IMAGE_PPA
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.tag }}:${{ github.sha }}
            ${{ matrix.tag }}:latest
  
  update-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2
      
      - name: Update image references
        run: |
          kustomize edit set image PROJECT/IMAGE_LOG=skinatro/log-output-gen:${{ github.sha }}
          kustomize edit set image PROJECT/IMAGE_LOR=skinatro/log-output-read:${{ github.sha }}
          kustomize edit set image PROJECT/IMAGE_PPA=skinatro/ping-pong-app:${{ github.sha }}
      
      - name: Commit updated kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: 'Update images to ${{ github.sha }}'
